name: house_work_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <5.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  json_annotation: ^4.4.0
  injectable: ^2.3.0
  path_provider: ^2.1.1
  retrofit: ^4.0.1
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  lint: ^2.1.2
  retrofit_generator: ^6.0.0

flutter:
  uses-material-design: true
